### ISSUE TITLE
Can't see output from JS runner

### ISSUE THREAD

**Issue by ccare** [exercism/research_experiment_1#97]
I've got the JS test runner deployed, but the output is disappearing. If you start the JS-1-A exercise and try the following code, you'll see that the response panel is blank.

```
// @ts-check

/**
 * Re-arranges the input array by moving an item from one position to another position.
 * Does not mutate the input array.
 *
 * @template T
 *
 * @param {T[]} array the input array
 * @param {number} from the position to move from
 * @param {number} to the position to move to
 *
 * @returns {T[]}
 */
export function arrange(array, from, to) {
  throw new Error('Implement the arrange function')
}

/**
 * Re-arranges the input array by moving an item from one position to another position.
 * Mutates the input array.
 *
 * @template T
 *
 * @param {T[]} array the input array
 * @param {number} from the position to move from
 * @param {number} to the position to move to
 *
 * @returns {T[]}
 */
export function rearrange(array, from, to) {
  throw new Error('Implement the rearrange function')
}
```

![Screenshot from 2020-02-03 21-36-54](https://user-images.githubusercontent.com/441154/73693353-f3c16800-46cd-11ea-8a95-59ee82cfd99f.png)

Looking at the websocket exchange, there's an OPS message of fail. The output, however, is just two line breaks.

![Screenshot from 2020-02-03 21-37-22](https://user-images.githubusercontent.com/441154/73693359-f754ef00-46cd-11ea-8e98-6f469a9864c0.png)

Looking at the DB, we have lots of data

```
...
     {"name"=>
       "magic-moves > rearrange > rearrange([ ♠, ♣, ♥, ♦, ✨ ], -3, -4): moves the ♥ (size - 3) one to the left (size - 4)",
      "output"=>nil,
      "status"=>"fail",
      "message"=>
       "Error: Implement the rearrange function\n" +
       "    at rearrange (/mnt/exercism-iteration/javascript-1-a.js:32:9)"},
     {"name"=>
       "magic-moves > rearrange > rearrange([ ♠, ♣, ♥, ♦, ✨ ], 0, 0): keeps ♠ (index 0) in place",
      "output"=>nil,
      "status"=>"fail",
      "message"=>
       "Error: Implement the rearrange function\n" +
       "    at rearrange (/mnt/exercism-iteration/javascript-1-a.js:32:9)"}]},
 created_at: Mon, 03 Feb 2020 21:33:22 UTC +00:00,
 updated_at: Mon, 03 Feb 2020 21:33:22 UTC +00:00,
 ops_status: 200,
 ops_message: "OK">
 ops_message: "OK">
```

**Comment by kntsoriano** [comment]
@ccare Hello, I've looked into this. The `results_status` isn't set, and that's why no output appears. For reference, the `results_status` is set here: app/services/submission_services/process_test_run.rb.

**Comment by ccare** [comment]
Working now!
